trigger:
- main # Cambia "main" por tu rama principal si es diferente.

variables:
  dockerRegistryServiceConnection: 'my-acr-connection'  # Asegúrate de tener este Service Connection configurado correctamente
  imageRepository: 'repositoryfunctionAz'  # Nombre del repositorio donde se almacenarán las imágenes
  containerRegistry: 'functionaz.azurecr.io'  # Nombre de tu Azure Container Registry
  tag: '$(Build.BuildId)'  # Etiqueta única por cada build

pool:
  vmImage: 'ubuntu-latest'

steps:
# Paso 1: Validar las credenciales de acceso
- task: DockerInstaller@0
  displayName: 'Instalar Docker CLI'

# Paso 2: Iniciar sesión en el ACR
- task: Docker@2
  displayName: 'Iniciar sesión en ACR'
  inputs:
    command: 'login'
    containerRegistry: '$(dockerRegistryServiceConnection)'

# Paso 3: Construir la imagen de contenedor
- task: Docker@2
  displayName: 'Construir la imagen Docker'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'  # Ajusta la ruta si el Dockerfile está en una carpeta diferente
    tags: |
      $(containerRegistry)/$(imageRepository):$(tag)  # Nombre completo de la imagen

# Paso 4: Publicar la imagen en ACR
- task: Docker@2
  displayName: 'Subir la imagen Docker a ACR'
  inputs:
    command: 'push'
    tags: |
      $(containerRegistry)/$(imageRepository):$(tag)  # Subir la imagen al ACR
